## 1.0 Intro to Numpy

- Creating arrays
- Multi-dimension arrays
- Random generated arrays
- Element-wise operations
  - Comparison operations
  - Logical operations
- Summary

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/opt/anaconda3/envs/zoomcamp-ml/lib/python3.9/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 3.2)

array([3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2])

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])