In [1]:
import numpy as np

vector multiplication

In [5]:

def vector_vector_multiplication(u, v):
  assert u.shape[0] == v.shape[0]
  n = u.shape[0]
  result = 0.0

  for i in range(n):
    result = result + u[i] * v[i]

  return result 

random vectors  

In [16]:

u = np.random.randint(5, size=(4, 1))
v = np.random.randint(5, size=(4, 1))
print(f'u: {u.shape}\nv: {v.shape}')

u: (4, 1)
v: (4, 1)


In [17]:
vector_vector_multiplication(u, v)

array([16.])

random matrices

u: (3, 4)
v: (4, 1)
[[1]
 [1]
 [3]
 [3]]


matrix-vector multiplication

In [26]:
def matrix_vector_multiplication(U, v):
  assert U.shape[1] == v.shape[0]
  # num_rows = U.shape[0]
  results = np.zeros(U.shape[0])
  for i in range(U.shape[0]):
    results[i] = vector_vector_multiplication(U[i], v)
  return results


In [32]:
print (f'{matrix_vector_multiplication(U, v)}\n{U.dot(v)}')

[26. 11. 14.]
[[26]
 [11]
 [14]]


In [28]:
U.dot(v)

array([[26],
       [11],
       [14]])

matrix multiplication

In [38]:
def matrix_multiplication(U, V):
  assert U.shape[1] == V.shape[0]

  rows, cols = U.shape[0], V.shape[1]
  results = np.zeros((rows, cols))

  for i in range(U.shape[0]):
    V_i = V[:,i]
    results[:,i] = vector_vector_multiplication(U, V_i)
  return results


In [43]:
U = np.random.randint(5, size=(3, 4))
V = np.random.randint(5, size=(4, 3))
print(f'u: {u.shape}\nv: {V.shape}')

u: (3, 4)
v: (3, 3)


In [45]:
matrix_multiplication(U, V)

AssertionError: 

In [44]:
U.dot(V)

ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)