In [1]:
import numpy as np
import pandas as pd

Question 1  
What's the version of NumPy that you installed?   
You can get the version information using the `__version__` field:

In [2]:
np.__version__

'1.22.1'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-11 22:35:53--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  2.54MB/s    in 0.6s    

2022-09-11 22:35:54 (2.54 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [5]:
!ls

_01_numpy.ipynb     _03_pandas.ipynb    data.csv
_02_algebra.ipynb   _04_assigment.ipynb


In [6]:
df = pd.read_csv('data.csv')

In [7]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [17]:
df.describe().round()

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count  11914.0    11845.0           11884.0          11908.0      11914.0   
mean    2010.0      249.0               6.0              3.0         27.0   
std        8.0      109.0               2.0              1.0          9.0   
min     1990.0       55.0               0.0              2.0         12.0   
25%     2007.0      170.0               4.0              2.0         22.0   
50%     2015.0      227.0               6.0              4.0         26.0   
75%     2016.0      300.0               6.0              4.0         30.0   
max     2017.0     1001.0              16.0              4.0        354.0   

       city mpg  Popularity       MSRP  
count   11914.0     11914.0    11914.0  
mean       20.0      1555.0    40595.0  
std         9.0      1442.0    60109.0  
min         7.0         2.0     2000.0  
25%        16.0       549.0    21000.0  
50%        18.0      1385.0    29995.0  
75%        22.0      2009.0    42231.0  
max       137.0      5657.0  2065902.0

In [15]:
df.Make.describe()

count         11914
unique           48
top       Chevrolet
freq           1123
Name: Make, dtype: object

Question 3: The most popular car manufacturers  
Description

In [27]:
df.groupby('Make')['Make'].count().sort_values(ascending=False).head()

Make
Chevrolet     1123
Ford           881
Volkswagen     809
Toyota         746
Dodge          626
Name: Make, dtype: int64

Question 4: Number of unique Audi car models

In [31]:
df[df.Make == 'Audi']['Model'].nunique()

34

Question 5: Number of columns with missing values

In [43]:
df.isnull().sum().values > 0

array([False, False, False,  True,  True,  True, False, False,  True,
        True, False, False, False, False, False, False])

Question 6
1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.
5. Has it changed?   

Hint: refer to existing mode and median functions to complete the task.

In [47]:
df['Engine Cylinders'].median()

6.0

In [51]:
df['Engine Cylinders'].mode()[0]

4.0

In [50]:
df['Engine Cylinders'].isnull().sum()

30

In [52]:
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode()[0], inplace=True)
df['Engine Cylinders'].isnull().sum()

0

In [53]:
df['Engine Cylinders'].median()

6.0

Question 7
1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the value of the first element of w?  
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [64]:
Q7 = df[df.Make == 'Lotus'][["Engine HP", "Engine Cylinders"]]
Q7.drop_duplicates(inplace=True)

In [67]:
X = Q7.to_numpy()

In [73]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [76]:
inv_XTX = np.linalg.inv(XTX)

In [77]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [81]:
y.dot(X.dot(inv_XTX))

array([  4.59494481, -63.56432501])